# Default WordPress Site Info
name: name         # Kubernetes Namespace (A-z,0-9,'-')
domain: domain     # Domain, e.g., mysite.com, mysite2.com, dev.anysite.com, etc.
storage: 10Gi      # Storage Size
ssd: false         # true=ssd, false=standard default
tls: true          # Set to 'true' for HTTPS/TLS/SSL

replicas: 1
maxSurge: 2
maxUnavailable: 0

wpRedisHost: 'redis.redis'
wpRedisPort: '6379'

wpMemoryLimit: '64M'
wpMaxMemoryLimit: '128M'

wpImage: "stcox/wordpress"
wpImageTag: "1.2"

ngImage: "stcox/nginx"
ngImageTag: "1.0"

dbUser: proxyuser
dbPass: proxyuserpassword

# Cloud SQL Instance Name
dbConn: project:region:instance  # from https://console.cloud.google.com/sql/instances
dbCred: '{}' # sql json credentials
