# Basic Site Info
name: mysite1-com         # Virtual Cluster Namespace (A-z,0-9,'-'), appears as namespace 'wp-mysite1-com'
domain: mydomain          # Domain, e.g., mysite1.com, mysite2.com, dev.anysite.com, etc.
storage: 5Gi              # Storage Size
tls: true                 # Set to true for HTTPS/TLS/SSL

maxSurge: 0
maxUnavailable: 1

# Requests & Limits - Memory & CPU:
#requestsMemory: 256Mi
#requestsCpu: 250m
#limitsMemory: 512Mi
#limitsCpu: 500m

##############################################################
# SET 'instanceConnectionName' below with an 'Instance connection name'
# from https://console.cloud.google.com/sql/instances.
# USAGE: [GCP Project]:[region]:[CloudSQL Name]
# E.G., myproject-123456:us-central1:mydb
##############################################################
instanceConnectionName: myproject:myregion:mydb
