apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: core
  labels:
    app: redis
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  ports:
    - port: 6379
      name: redis
  selector:
    app: redis
    tier: mysql-cache
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  namespace: core
  labels:
    app: redis
    tier: mysql-cache
spec:
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: redis
        tier: mysql-cache
    spec:
      containers:
      - image: redis:4
        name: redis
        ports:
        - containerPort: 6379
          name: redis
