apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wp-{{ .Values.name }}
  namespace: wp-{{ .Values.name }}
  labels:
    app: wp-{{ .Values.name }}
    tier: frontend
    track: stable
spec:
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: wp-nginx
        app: wp-{{ .Values.name }}
        tier: frontend
        track: stable
    spec:
      containers:
      - image: stcox/wordpress-redis:1.2
        name: wp
        env:
        - name: WORDPRESS_DB_HOST
          value: 127.0.0.1:3306 # this must be the FQDN of the mariadb Service
        - name: WORDPRESS_DB_NAME
          value: wp_{{ .Values.name }}
        - name: WORDPRESS_DB_USER
          value: proxyuser
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: password
        #resources:
        #  requests:
        #    memory: {{ .Values.requestsMemory | quote }}
        #    cpu: {{ .Values.requestsCpu | quote }}
        #  limits:
        #    memory: {{ .Values.limitsMemory | quote }}
        #    cpu: {{ .Values.limitsCpu | quote }}
        volumeMounts:
        - name: wp-persistent-storage
          mountPath: /var/www/html
        - name: php
          mountPath: /usr/local/etc/php/conf.d
        - name: cache
          mountPath: /var/run/nginx-cache
      - image: gcr.io/cloudsql-docker/gce-proxy:1.11
        name: cloudsql-proxy
        command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                  "-instances={{ .Values.instanceConnectionName }}=tcp:3306",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
        - name: cloudsql-instance-credentials
          mountPath: /secrets/cloudsql
          readOnly: true
        - name: ssl-certs
          mountPath: /etc/ssl/certs
        - name: cloudsql
          mountPath: /cloudsql
      - image: stcox/nginx-pagespeed:1.1
        name: wp-nginx
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: wp-persistent-storage
          mountPath: /var/www/html
        - name: nginx
          mountPath: /etc/nginx
        - name: nginx-conf-d
          mountPath: /etc/nginx-conf/conf.d
        - name: nginx-global
          mountPath: /etc/nginx-conf/global
        - name: nginx-html
          mountPath: /etc/nginx-conf/html
        - name: cache
          mountPath: /var/run/nginx-cache
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials
      - name: cloudsql
        emptyDir:
      - name: ssl-certs
        hostPath:
          path: /etc/ssl/certs
      - name: wp-persistent-storage
        persistentVolumeClaim:
          claimName: wp-{{ .Values.name }}-pv-claim
      - name: php
        configMap:
          name: php
      - name: nginx
        configMap:
          name: nginx
      - name: nginx-conf-d
        configMap:
          name: nginx-conf-d
      - name: nginx-global
        configMap:
          name: nginx-global
      - name: nginx-html
        configMap:
          name: nginx-html
      - name: cache
        emptyDir:
          medium: "Memory"
