apiVersion: v1
kind: Secret
metadata:
  name: cloudsql-db-credentials
  namespace: wp-{{ .Values.name }}
  labels:
    app: wp-{{ .Values.name }}
type: Opaque
data:
  username: |-
    {{ .Files.Get ".dbuser" | b64enc }}
  password: |-
    {{ .Files.Get ".dbpw" | b64enc }}
