apiVersion: v1
kind: Secret
metadata:
  name: cloudsql-db-credentials
  namespace: wp-{{ .Values.name }}
  labels:
    app: wp-{{ .Values.name }}
type: Opaque
data:
  user: |-
    {{ .Files.Get "wp-secrets/.dbuser" | b64enc }}
  password: |-
    {{ .Files.Get "wp-secrets/.dbpw" | b64enc }}
