apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-{{ .Values.name }}-pv
  labels:
    app: wp-{{ .Values.name }}
spec:
  capacity:
    storage: {{ .Values.storage }}
  accessModes:
    - ReadWriteOnce
  storageClassName: slow
  gcePersistentDisk:
    pdName: {{ .Values.name }}
    fsType: ext4
