apiVersion: v1
data:
  proxy-connect-timeout: {{ .Values.proxy-connect-timeout | quote }}
  proxy-read-timeout: {{ .Values.proxy-read-timeout | quote }}
  proxy-send-timeout: {{ .Values.proxy-send-timeout | quote }}
  proxy-body-size: {{ .Values.proxy-body-size | quote }}
  server-name-hash-bucket-size: {{ .Values.server-name-hash-bucket-size | quote }}
  hsts-preload: {{ .Values.hsts-preload | quote }}
kind: ConfigMap
metadata:
  namespace: nginx-ingress
  name: nginx
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
